<x-admin-layout>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque rem itaque, tempore ipsa quasi consequuntur deleniti, nisi placeat cupiditate at obcaecati sequi dolore consequatur facilis eos aperiam esse reiciendis veniam?</p>
    <p>Ad molestiae quis dolor tempora reprehenderit in et. Provident asperiores obcaecati inventore nemo veritatis rem nesciunt quisquam ratione. Eaque deleniti delectus laboriosam quibusdam sapiente, ipsa voluptatum. Corrupti veritatis beatae delectus.</p>
    <p>Dolore reprehenderit labore at quibusdam ipsa, commodi placeat, laboriosam aut officiis nulla, adipisci neque ex nisi necessitatibus. Et natus vero magni corporis placeat, illo, accusantium beatae, quidem odio ipsam non.</p>
    <p>Voluptatum sunt tenetur iusto minima quibusdam doloremque harum soluta at dicta, ipsam ad expedita, maiores laboriosam aliquid dolores dolore nam inventore, nisi ipsum deserunt modi sint autem! Quibusdam, officiis rem!</p>
    <p>Sunt rerum sit pariatur quibusdam distinctio ex voluptate est quis tempore dolores quasi aut quod optio voluptatem, minus nihil nemo voluptas ad incidunt recusandae quam minima, eum quae sint! Expedita.</p>
    <p>Non delectus quibusdam provident dolor dolorem, magni quisquam reprehenderit velit omnis sunt eum enim molestiae nihil nobis magnam dolores quaerat atque perspiciatis esse, porro doloribus blanditiis. Provident itaque ipsam officia!</p>
    <p>Ab praesentium, quidem accusantium nihil ipsa nobis dicta. Voluptate doloribus dolorem perferendis architecto quasi consequatur id veritatis animi reiciendis voluptatum. Voluptas aspernatur nostrum sed natus optio similique aliquid consequatur error!</p>
    <p>Corrupti numquam, vero natus veritatis quisquam maxime porro dicta quaerat praesentium earum dignissimos sequi tempora hic exercitationem magnam non error quis eaque assumenda, architecto ratione expedita deleniti similique. Perferendis, pariatur.</p>
    <p>Nulla, illum ex autem molestiae repudiandae impedit provident reiciendis necessitatibus fugiat odit suscipit in quis quo, esse a ad veritatis eos pariatur sunt sit ea illo! Sit reiciendis hic possimus.</p>
    <p>Dolore reprehenderit voluptatem quae id, deleniti fugit reiciendis veritatis iusto corporis a suscipit aut illum non voluptates optio tempore impedit modi! Earum modi voluptatem dignissimos? Illum consequatur reiciendis recusandae rerum.</p>
    <p>Sunt similique, consequuntur facilis architecto consectetur eum, enim consequatur, rerum quam dolor sequi eos saepe debitis doloribus aliquid nostrum perferendis tempora labore? Quisquam, autem. Ducimus ipsa omnis nisi quidem suscipit!</p>
    <p>Veniam similique quam quaerat quia. Tempore ducimus voluptates molestiae quos ipsam blanditiis excepturi itaque. Assumenda, repellat iusto. Ea, veniam ipsa nobis enim facere iusto, nemo tempora iure deleniti, aut voluptate?</p>
    <p>Laboriosam illo, id voluptas corporis asperiores accusamus quos. Dolore odit magnam natus inventore cum. Accusantium totam placeat deserunt, provident debitis voluptatum suscipit atque est id perspiciatis maiores qui recusandae officiis.</p>
    <p>Laudantium ea natus vero vel maiores beatae voluptates ipsam libero maxime, hic animi enim sed magnam asperiores perferendis dicta optio explicabo quasi. Reiciendis velit similique sapiente dolorum, nulla cupiditate atque!</p>
    <p>Quasi, voluptas quidem est dolores suscipit sint inventore voluptatem, quod, magni placeat distinctio. Temporibus alias quas incidunt ratione eligendi exercitationem consequuntur, magnam magni esse dolorem delectus, veritatis obcaecati, beatae ipsam.</p>
    <p>Sit qui earum ipsam numquam beatae quasi tempora quos eos quod vel maxime nam, fugiat eum suscipit minus ipsum inventore quibusdam! Voluptatum sapiente perferendis architecto tenetur officia aperiam suscipit molestias?</p>
    <p>Sit cum alias nisi mollitia, deleniti minima dignissimos, sunt enim amet at placeat reiciendis aliquam perferendis. Corrupti distinctio molestias ab, reprehenderit architecto alias, voluptatum facere veritatis nemo consequatur ad animi.</p>
    <p>Nulla, maxime dicta cumque eius ex possimus. Voluptatum praesentium maxime deserunt non itaque, dolore magni sit officia ullam reprehenderit harum, corporis quasi ad quos blanditiis quis et impedit eligendi assumenda.</p>
    <p>Eius quae enim id, alias sequi porro reprehenderit dolorem vel. Nostrum earum repellat dignissimos doloribus at deserunt ipsa nihil vel voluptate. Tempore sapiente ipsum distinctio minus similique voluptatum neque. Hic.</p>
    <p>Esse iusto laborum nesciunt consectetur in est amet nisi, atque, quis suscipit asperiores pariatur architecto optio provident beatae expedita quidem vitae natus aliquid voluptatibus assumenda corrupti, maiores deserunt. Ullam, explicabo!</p>
</x-admin-layout>
